baseURL = "https://gkits.github.io/PavoSQL"
languageCode = "en-us"
title = "PavoSQL"

enableGitInfo = true
disablePathToLower = true

[markup]
[markup.goldmark.renderer]
unsafe = true
[markup.tableOfContents]
startLevel = 1

[menu]
[[menu.after]]
name = "Github"
url = "https://github.com/gKits/PavoSQL"
weight = 10

[module]
[[module.imports]]
path = "github.com/alex-shpak/hugo-book"


[params]
favicon = "favicon.ico"
BookTheme = "dark"
BookToc = true
BookSection = "docs"
BookLogo = "PavoSQL.png"
BookRepo = "github.com/gKits/PavoSQL"
BookCommitPath = "commit"
[params.meta]
favicon = false
